title : WildLaws Potoplio
description: 'Welcome to Wild Space!!'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
plugins: [jekyll-gist]
permalink: /:year/:month/:title.html
